services:
  - type: web
    name: backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:mand: ""
      - key: FLASK_ENV
        value: production
      - key: FLASK_APPion
        value: app.pyP
      - key: GEMINI_API_KEY
        fromDatabase: GEMINI_API_KEY
    autoDeploy: true: GEMINI_API_KEY
    repo:eploy: true
      branch: main
      rootDir: backend
